/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function buildIndex(path: string): void

export interface CollectionConfig {
  path: string
  dimensions: number
  indexType: string
  metric: string
}

export interface CollectionStats {
  count: number
  dimensions: number
  fileSizeBytes: number
}

export declare function createCollection(config: CollectionConfig): void

export declare function deleteVector(path: string, id: string): boolean

export declare function insertVector(path: string, id: string, vector: Float32Array): void

export declare function search(path: string, query: Float32Array, k: number, efSearch?: number | undefined | null): Array<SearchResult>

export interface SearchResult {
  id: string
  score: number
}

export declare function stats(path: string): CollectionStats
